ebook_store_proj/ebook_store_app/urls.py
from django.urls import path
from ebook_store_app import views


app_name = 'ebook_store_app'

urlpatterns = [
    path('home/', views.book_view, name='home'),
    path('about/', views.about_view, name='about'),
    path('user-view/', views.UserListView.as_view(), name='user-view'),
    path('update-user/<int:pk>/', views.UpdateUserView.as_view(), name='update-user'),
    path('delete-user/<int:pk>/', views.DeleteUserView.as_view(), name='delete-user'),
    
    path('add-book/', views.AddBookView.as_view(), name='add-book'),
    path('update-book/<int:pk>/', views.UpdateBookView.as_view(), name='update-book'),
    path('delete-book/<int:pk>/', views.DeleteBookView.as_view(), name='delete-book'),
    path('detail-book/<int:book_id>/', views.book_detail, name='detail-book'),

    path('add-author/', views.AddAuthorView.as_view(), name='add-author'),
    path('delete-author/<int:pk>/', views.DeleteAuthorView.as_view(), name='delete-author'),
    path('update-author/<int:pk>/', views.UpdateAuthorView.as_view(), name='update-author'),
    path('author-view/', views.AuthorListView.as_view(), name='author-view'),

    path('add-genre/', views.AddGenreView.as_view(), name='add-genre'),
    path('delete-genre/<int:pk>/', views.DeleteGenreView.as_view(), name='delete-genre'),
    path('update-genre/<int:pk>/', views.UpdateGenreView.as_view(), name='update-genre'),
    path('genre-view/', views.GenreListView.as_view(), name='genre-view'),

    path('add-publisher/', views.AddPublisherView.as_view(), name='add-publisher'),
    path('delete-publisher/<int:pk>/', views.DeletePublisherView.as_view(), name='delete-publisher'),
    path('update-publisher/<int:pk>/', views.UpdatePublisherView.as_view(), name='update-publisher'),
    path('publisher-view/', views.PublisherListView.as_view(), name='publisher-view'),

    path('update-item/', views.update_item, name='update_item'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('process-order/', views.process_order, name='process_order'),

    path('payment/', views.payment, name='payment'),
    path('book-rate/<int:book_id>/', views.book_rate, name='book_rate'),
    path('order-view/', views.OrderListView.as_view(), name='order-view'),
    path('best-sellers/', views.best_sellers, name='best-sellers'),
    path('best-sellers/<int:genre_id>/', views.best_sellers_genre, name='best-sellers-genre'),
]

ebook_store_proj/ebook_store_proj/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include

from ebook_store_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ebook_store_app.urls', namespace='ebook_store_app')),
    path('register/', views.register_user, name="register"),
    path('login/', views.login_user, name="login_user"),
    path('logout/', views.logout_user, name="logout"),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ebook_store_proj/ebook_store_app/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm

from .models import UserProfile, Book, Author, Genre, Publisher


class CreateUserForm(UserCreationForm):
    email = forms.EmailField(max_length=50, help_text='Required')
    class Meta:
        model = UserProfile
        fields = ("email", "name" ,"username", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-input'


class AddBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'


class AddAuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = '__all__'


class AddGenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = '__all__'


class AddPublisherForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = '__all__'

ebook_store_proj/ebook_store_app/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.http import HttpResponseRedirect, JsonResponse

import json, datetime, stripe

from django.core.paginator import Paginator, EmptyPage

from django.urls import reverse, reverse_lazy

from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from .forms import *
from .models import *
from .filters import BookFilter
from .utils import cart_data, guest_order, UserAccess



def register_user(request):
    if request.user.is_authenticated:
        return redirect('ebook_store_app:home')

    form = CreateUserForm()

    if request.method == 'POST':
        if UserProfile.objects.filter(email=request.POST['email']).exists():
            old_user = UserProfile.objects.get(email=request.POST['email'], password="")
            old_user.set_password(request.POST['password1'])
            old_user.name = request.POST['name']
            old_user.save()
            return redirect('login_user')
        else:
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                return redirect('login_user')

    context = {'form':form}
    return render(request, './account/register.html', context)


def login_user(request):
    if request.user.is_authenticated:
        return redirect('ebook_store_app:home')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user:
            login(request, user)
            return redirect('ebook_store_app:home')
        else:
            messages.info(request, 'USERNAME OR PASSWORD IS INCORRECT!!')

    return render(request, "./account/login.html", {})


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('ebook_store_app:home'))


class UserListView(UserAccess, ListView):
    model = UserProfile
    context_object_name = 'users'
    template_name = 'account/user-view.html'


class UpdateUserView(UserAccess, UpdateView):
    model = UserProfile
    template_name = 'account/update-user.html'
    fields = ['username', 'email', 'status']
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('ebook_store_app:user-view')


class DeleteUserView(UserAccess, DeleteView):
    model = UserProfile
    pk_url_kwarg = 'pk'
    template_name = 'account/delete-user.html'
    success_url = reverse_lazy('ebook_store_app:user-view')


def book_view(request):
    genres = Genre.objects.all()
    books = Book.objects.all()
    data = cart_data(request)
    cart_items = data['cart_items']
    my_filter = BookFilter(request.GET, queryset=books)
    books = my_filter.qs
    my_page = Paginator(books, 8)
    page_number = request.GET.get('page', False)
    all_pages = my_page.num_pages

    try:
        books = my_page.page(page_number)
    except EmptyPage:
        books = my_page.page(1)

    context = {'books':books, 'genres':genres , 'cart_items':cart_items, 'my_filter':my_filter, 'all_pages':all_pages}

    return render(request, './home/home.html', context)
    

def book_detail(request, book_id):
    book = Book.objects.get(id=book_id)
    related_books = Book.objects.filter(genre_id=book.genre_id).exclude(id=book_id)
    data = cart_data(request)
    cart_items = data['cart_items']
    
    context = {'book':book, 'related_books':related_books, 'cart_items':cart_items}
    return render(request, './home/book-detail.html', context)


class AddBookView(UserAccess, CreateView):
    model = Book
    form_class = AddBookForm
    template_name = 'actions/add-book.html'
    success_url = reverse_lazy('ebook_store_app:home')


class UpdateBookView(UserAccess, UpdateView):
    model = Book
    template_name = 'actions/update-book.html'
    fields = '__all__'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('ebook_store_app:home')


class DeleteBookView(UserAccess, DeleteView):
    model = Book
    pk_url_kwarg = 'pk'
    template_name = 'actions/delete-book.html'
    success_url = reverse_lazy('ebook_store_app:home')


def about_view(request):
    data = cart_data(request)
    cart_items = data['cart_items']
    return render(request, './info/about.html', {'cart_items':cart_items})


class AuthorListView(ListView):
    model = Author
    context_object_name = "authors"
    template_name = 'author/author-view.html'


class AddAuthorView(UserAccess, CreateView):
    model = Author
    fields = '__all__'
    template_name = 'author/add-author.html'
    success_url = reverse_lazy('ebook_store_app:author-view')


class UpdateAuthorView(UserAccess, UpdateView):
    model = Author
    template_name = 'author/update-author.html'
    fields = '__all__'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('ebook_store_app:author-view')


class DeleteAuthorView(UserAccess, DeleteView):
    model = Author
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('ebook_store_app:author-view')
    template_name = 'author/delete-author.html'


class GenreListView(ListView):
    model = Genre
    context_object_name = "genres"
    template_name = 'genre/genre-view.html'


class AddGenreView(UserAccess, CreateView):
    model = Genre
    fields = '__all__'
    template_name = 'genre/add-genre.html'
    success_url = reverse_lazy('ebook_store_app:genre-view')


class UpdateGenreView(UserAccess, UpdateView):
    model = Genre
    template_name = 'genre/update-genre.html'
    fields = '__all__'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('ebook_store_app:genre-view')


class DeleteGenreView(UserAccess, DeleteView):
    model = Genre
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('ebook_store_app:genre-view') 
    template_name = 'genre/delete-genre.html'


class PublisherListView(ListView):
    model = Publisher
    context_object_name = "publishers"
    template_name = 'publisher/publisher-view.html'


class AddPublisherView(UserAccess, CreateView):
    model = Publisher
    fields = '__all__'
    template_name = 'publisher/add-publisher.html'
    success_url = reverse_lazy('ebook_store_app:publisher-view')


class UpdatePublisherView(UserAccess, UpdateView):
    model = Publisher
    template_name = 'publisher/update-publisher.html'
    fields = '__all__'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('ebook_store_app:publisher-view')


class DeletePublisherView(UserAccess, DeleteView):
    model = Publisher
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('ebook_store_app:publisher-view') 
    template_name = 'publisher/delete-publisher.html'


def cart(request):
    data = cart_data(request)
    items = data['items']
    order = data['order']
    cart_items = data['cart_items']

    context = {'items':items, 'order':order, 'cart_items':cart_items}
    return render(request, './home/cart.html', context)


def checkout(request):
    data = cart_data(request)
    items = data['items']
    order = data['order']
    cart_items = data['cart_items']

    context = {'items':items, 'order':order, 'cart_items':cart_items}
    return render(request, './home/checkout.html', context)


def update_item(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    customer = request.user
    product = Book.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer_id=customer, complete=False) 
    orderItem, created = OrderDetails.objects.get_or_create(order_id=order, book_id=product)

    if action == 'add':
        orderItem.total = (orderItem.total + 1)
    elif action == 'remove':
        orderItem.total = (orderItem.total - 1)

    orderItem.save()

    if orderItem.total <= 0:
        orderItem.delete()

    return JsonResponse('Item added', safe=False)


def process_order(request):
    number = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(customer_id=customer, complete=False) 

    else:
        customer, order = guest_order(request, data)

    total = float(data['form']['total'])
    order.order_number = number

    if total == float(order.get_cart_total):
        order.complete = True 
            
    order.save()
    Shipping.objects.create(
        customer_id=customer,
        order_id=order,
        adress=data['shipping']['adress'],
        city=data['shipping']['city'],
        country=data['shipping']['country'],
        zip_code=data['shipping']['zip_code'],
    )

    return JsonResponse("Order completed", safe=False)

def payment(request):
    if request.user.is_authenticated:
        user = request.user
    else:
        order_user = Order.objects.filter(payed=False, complete=True).first() 
        user = order_user.customer_id
    
    order = Order.objects.filter(customer_id=user, payed=False, complete=True).first()
    
    if request.method == 'POST':
        order.payed = True
        order.save()
        
        customer = stripe.Customer.create(
            email=user.email,
            name=user.username,
            source=request.POST['stripeToken']
        )
        charge = stripe.Charge.create(
            customer=customer,
            amount=int(order.get_cart_total * 100),
            currency='usd',
            description='Charge for buying book/s'
        )
        return redirect(reverse('ebook_store_app:home'))
        
    return render(request, './home/payment.html', {})


@login_required
def book_rate(request, book_id):
    user = request.user
    book = Book.objects.get(id=book_id)
    mark = request.POST['rate']
    
    if(BookRating.objects.filter(customer_id=user, book_id=book)):

ebook_store_proj/ebook_store_app/templates/home/book-detail.html
<title>Ebook store</title>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/home/single.css' %}"/> 

<div class="home">
    <div class="small-container single-product">
        <div class="row">
            <div class="column">
                <img src="{{ book.picture.url }}" alt="{{ book.title }}">
            </div>
            <div class="column">
                <h1>{{ book.title }}</h1>
                <h2>{{ book.author_id.first_name }} {{ book.author_id.last_name }}</h2>
                <h3>Genre: <span style="color:red;font-size: larger;">{{ book.genre_id }}</span></h3>
                <h4>${{ book.price }}</h4>
                <button data-product="{{ book.id }}" data-action="add" class="cart-btn update-cart">Add to cart</button><br><br>
                <h3>Description</h3><br>
                <p>{{ book.description }}</p>
            </div>
        </div>
    </div>
    <hr>
    <div class="small-contaier">
        <div class="row row-2">
            <h2 class="title">Same genre</h2> 
        </div>
        <div class="row">
            {% for book in related_books %}
                <div class="col">
                    <a href="{% url 'ebook_store_app:detail-book' book.id %}"><img src="{{ book.picture.url }}" alt="{{ book.title }}" style="width: 10%;"></a>
                    <h4 class="product">{{ book.title }}</h4>
                    <h4 class="product">{{ book.author_id.first_name }} {{ book.author_id.last_name }}</h4>
                    <p class="price">${{ book.price }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

ebook_store_proj/ebook_store_app/templates/home/cart.html
<title>Cart</title>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/home/cart-style.css' %}">
	
<main class="page">
    <section class="shopping-cart dark">
        <div class="container">
            <div class="block-heading">
                <h2>Shopping Cart</h2>
            </div>
            <div class="content">
                <div class="row">
                    <div class="col-md-12 col-lg-8">
                        <div class="items">
                            {% for item in items %}
                            <div class="product">
                                <div class="row">
                                    <div class="col-md-3">
                                        <img class="img-fluid mx-auto d-block image" src="{{ item.book_id.picture.url }}">
                                    </div>
                                    <div class="col-md-8">
                                        <div class="info">
                                            <div class="row">
                                                <div class="col-md-5 product-name">
                                                    <div class="product-name">
                                                        <a href="{% url 'ebook_store_app:detail-book' item.book_id.id %}">{{ item.book_id.title }}</a>
                                                        <div class="product-info">
                                                            <div>Author: <span class="value">{{ item.book_id.author_id.first_name }} {{ item.book_id.author_id.last_name }}</span></div>
                                                            <div>Publisher: <span class="value">{{ item.book_id.publisher_id.company_name }}</span></div>
                                                            <div>Genre: <span class="value">{{ item.book_id.genre_id.genre_type }}</span></div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-4 quantity">
                                                    {{ item.order_id.total }}
                                                    <img data-product="{{ item.book_id.id }}" data-action="add" class="chg-quantity update-cart" src="{% static 'media/arrow-up.png' %}">
                                                    <img data-product="{{ item.book_id.id }}" data-action="remove" class="chg-quantity update-cart" src="{% static 'media/arrow-down.png' %}">
                                                </div>
                                                <div class="col-md-3 price">
                                                    <span>${{ item.get_total }}</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-md-12 col-lg-4">
                        <div class="summary">
                            <h3>Summary</h3>
                            <div class="summary-item"><span class="text">Total items</span><span class="price">{{ order.get_cart_items }}</span></div>
                            <div class="summary-item"><span class="text">Total</span><span class="price">${{ order.get_cart_total }}</span></div><br>
                            <a href="/checkout" class="btn btn-primary btn-lg btn-block">Checkout</a>
                            <a href="/home" class="btn btn-primary btn-lg btn-block btn-back">&#8592; Continue shopping</a>
                        </div>
                    </div>
                </div> 
            </div>
        </div>
    </section>
</main>
{% endblock %}

ebook_store_proj/ebook_store_app/templates/home/checkout.html
<title>Checkout</title>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/home/checkout.css' %}">

<main class="page payment-page">
    <section class="payment-form dark">
      <div class="container">
        <div class="block-heading">
          <h2>Checkout</h2>
        </div>
        <form id="form">
          {% csrf_token %}
          <div class="products">
            <h3 class="title">Checkout</h3>
            {% for item in items %}
            <div class="item">
              <span class="price">${{ item.book_id.price }}</span>
              <p class="item-name">{{ item.book_id.title }}</p>
              <p class="item-description">{{ item.book_id.author_id.first_name }} {{ item.book_id.author_id.last_name }}</p>
            </div>
            {% endfor %}
            <div class="total">Total<span class="price">${{ order.get_cart_total }}</span></div>
          </div>
          <hr>
          <div class="products">
            <h3 class="title">User detail</h3>
            {% if not request.user.is_authenticated %}
              <input type=text class="form-input" name="username" placeholder="Username"><br>
              <input type=email class="form-input" name="email" placeholder="Email"><br>
            {% endif %}
            <input type=text class="form-input" name="adress" placeholder="Adress"><br>
            <input type=text class="form-input" name="city" placeholder="City"><br>
            <input type=text class="form-input" name="country" placeholder="Country"><br>
            <input type=text class="form-input" name="zip_code" placeholder="Zip code">
          </div>
        <div class="form-group col-sm-12">
          <button type="submit" class="btn btn-primary btn-block make-payment">Proceed</button>
          <button type="submit" formaction="/cart" class="btn btn-primary btn-block">Back to cart</button>
        </form>
      </div>
    </section>
  </main>
<script>
  var total = '{{order.get_cart_total}}';
</script>
<script type="text/javascript" src="{% static 'js/checkout.js' %}"></script>
{% endblock %}

ebook_store_proj/ebook_store_app/templates/home/home.html
<title>Ebook store</title>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">

<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<link rel="stylesheet" type="text/css" href="{% static 'css/home/home-style.css' %}"/> 

<div id="demo" class="carousel slide" data-ride="carousel">
    <ul class="carousel-indicators">
      <li data-target="#demo" data-slide-to="0" class="active"></li>
      <li data-target="#demo" data-slide-to="1"></li>
      <li data-target="#demo" data-slide-to="2"></li>
    </ul>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="../../static/media/Harry.jpg" alt="The_Great_Gatsby"  width="1100" height="500">
      </div>
      <div class="carousel-item">
        <img src="../../static/media/Catcher-in-the-Rye-Marathon-Reading.png" alt="One_Hundred_Years_Of_Solitude" width="1100" height="500">
      </div>
      <div class="carousel-item">
        <img src="../../static/media/1200px-To_Kill_a_Mockingbird_(first_edition_cover).jpg" alt="Beloved" width="1100" height="500">
      </div>
    </div>
    <a class="carousel-control-prev" href="#demo" data-slide="prev">
      <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#demo" data-slide="next">
      <span class="carousel-control-next-icon"></span>
    </a>
</div>
<hr>
<div id="my-btn-container">
  {% if request.user.is_authenticated %}
    {% if request.user.status == 'Admin' %} 
      <a class="action-btn add-btn" href="{% url 'ebook_store_app:add-book' %}">Add book</a>
      <a class="action-btn add-btn" href="{% url 'ebook_store_app:add-publisher' %}">Add publisher</a>
      <a class="action-btn add-btn" href="{% url 'ebook_store_app:add-genre' %}">Add genre</a>
      <a class="action-btn add-btn" href="{% url 'ebook_store_app:add-author' %}">Add author</a><br><br>
    {% endif %}
  {% endif %}
  <a class="action-btn add-btn" href="{% url 'ebook_store_app:best-sellers' %}">Best sellers</a><br>
  Best sellers for genre
  {% for genre in genres %}
    <a class="action-btn add-btn" href="{% url 'ebook_store_app:best-sellers-genre' genre.id %}">{{ genre.genre_type }}</a>
  {% endfor %}
<hr>
<div class="dropdown">
    <form method="GET">
        Genres {{ my_filter.form.genre_id }}
        Authors {{ my_filter.form.author_id }}
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</div>
<br>
<div class="container">
  <div class="row clearfix">
    {% for book in books %}
      <div class="col-lg-3 col-md-4 col-sm-12">
          <div class="card product_item">
              <div class="body">
                  <div class="cp_img">
                    <a href="{% url 'ebook_store_app:detail-book' book.id %}">
                      
                      {% if book.picture %}
                        <img src="{{ book.picture.url }}" alt="{{ book.title }}" class="img-fluid">
                      {% endif %}
                    </a>
                      <div class="hover">      
                          {% if request.user.is_authenticated %}
                            {% if request.user.status == 'Admin' %}
                              <a href="{% url 'ebook_store_app:delete-book' book.id %}" class="btn btn-primary btn-sm waves-effect"><i class="fa fa-trash"></i></a>
                              <a href="{% url 'ebook_store_app:update-book' book.id %}" class="btn btn-primary btn-sm waves-effect"><i class="fa fa-edit" style="font-size:12px"></i></a>
                            {% endif %}
                          {% endif %}
                      </div>
                  </div>
                  <div class="product_details">
                      <h5>{{ book.title }}</h5>
                      <ul class="product_price list-unstyled">
                        <li class="old_price">${{ book.price }}</li>
                        <li class="old_price">{{ book.get_mean_value }}/5</li>
                      </ul>
                      {% if request.user.is_authenticated %}
                        <form action="{% url 'ebook_store_app:book_rate' book.id %}" method="POST">
                          {% csrf_token %}
                          <ul class="product_price list-unstyled">
                            <li>
                              <div class="star-wrapper">
                                <button class="s5" type="submit" name="rate" value="5">★</button>
                                <label for="star5" title="text"></label>
                                <button class="s4" type="submit" name="rate" value="4">★</button>
                                <label for="star4" title="text"></label>
                                <button class="s3" type="submit" name="rate" value="3">★</button>
                                <label for="star3" title="text"></label>
                                <button class="s2" type="submit" name="rate" value="2">★</button>
                                <label for="star2" title="text"></label>
                                <button class="s1" type="submit" name="rate" value="1">★</button>
                                <label for="star1" title="text"></label>
                            </div>
                          </li>
                        </ul>
                      </form>
                      {% endif %}
                  </div>
              </div>
          </div>
      </div>
      {% endfor %}
  </div>
</div>
<div class="page-btn">
  {% if books.has_previous %}
      <a href="{% url 'ebook_store_app:home' %}?page={{ books.previous_page_number }}"><span>&#8592;</span></a>
  {% endif %}
  {% with i|center:all_pages as range %}
      {% for i in range %}
        <a href="{% url 'ebook_store_app:home' %}?page={{ forloop.counter }}"><span>{{ forloop.counter }}</span></a>    
      {% endfor %}
  {% endwith %}
  {% if books.has_next %}
    <a href="{% url 'ebook_store_app:home' %}?page={{ books.next_page_number }}"><span>&#8594;</span></a>
  {% endif %}
</div>
{% endblock %}

ebook_store_proj/ebook_store_app/templates/home/payment.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Payment</title>
    <link rel="icon" href="{% static './media/logo.png' %}" type="png">
    <link rel="stylesheet" type="text/css" href="{% static 'css/home/payment.css' %}"/>
    
</head>
<body>
    
<script src="https://js.stripe.com/v3/"></script>
<form action="{% url 'ebook_store_app:payment' %}" method="post" id="payment-form">
  <h2>Payment</h2>
    {% csrf_token %}
    <div class="form-row">
      <label for="card-element">
        Credit or debit card
      </label>
      <div id="card-element">
      </div>
      <div id="card-errors" role="alert"></div>
    </div>
    <button>Submit</button>
</form>
<script type="text/javascript" src="{% static 'js/payment.js' %}"></script>
</body>
</html>